StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{64DAC016AFDFB8F5}" {
   Id "BFV-Vehicle_M2A2_BUSK_Name"
   Target_en_us "M2A2 (BUSK)"
   Modified 1692057733
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{63106177059DD437}" {
   Id "BFV-Vehicle_M2A2_Name"
   Target_en_us "M2A2"
   Modified 1691952809
   Author "thoma"
   LastChanged "luis_"
  }
  CustomStringTableItem "{64D925C55525C007}" {
   Id "BFV-Vehicle_M2A3_BUSK3_Name"
   Target_en_us "M2A3 (BUSK III)"
   Modified 1691953031
   Author "luis_"
   LastChanged "luis_"
  }
  CustomStringTableItem "{64D925C5A0858106}" {
   Id "BFV-Vehicle_M2A3_Name"
   Target_en_us "M2A3"
   Modified 1691952814
   Author "luis_"
   LastChanged "luis_"
  }
 }
}